# /**
#  * Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#  *
#  * Licensed under the Apache License, Version 2.0 (the "License");
#  * you may not use this file except in compliance with the License.
#  * You may obtain a copy of the License at
#  *
#  *     http://www.apache.org/licenses/LICENSE-2.0
#  */

## Default values for schema-registry.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

replicas: 2

image:
  repository: pravega/schema-registry
  tag: 0.0.1
  pullPolicy: IfNotPresent

## Service account name and whether to create it.
serviceAccount:
  create: true
  name: schema-registry
  annotations:

service:
  type: LoadBalancer
  port: 9092

client:
  loadDynamic: false
  method: ""
  token: ""

controllerUri: tcp://localhost:9090
storeType: Pravega

authentication:
  enabled: false
  ## following values are considered only when
  ## authentication is enabled
  passwordAuthSecret:
  userPasswordFile:
  tokenSigningKey:

tls:
  enabled: false
  ## following values are considered only when
  ## tls is enabled
  secret:
  certFile:
  trustStore:
  keyFile:
  keyPasswordFile:
