{{- $ingress := .Values.ingress -}}
{{- $svc := .Values.service -}}
{{- if $ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "schema-registry.fullname" . }}
  labels:
{{ include "schema-registry.commonLabels" . | indent 4 }}
  annotations:
{{ toYaml $ingress.annotations | indent 4 }}
spec:
  {{- if $ingress.tls }}
  tls:
    {{- range $ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingress.path }}
            backend:
              serviceName: {{ template "schema-registry.fullname" $ }}
              servicePort: {{ $svc.port }}
    {{- end }}
{{- end }}
